<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function axelerant_assignment_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the axelerant_assignment module.
    case 'help.page.axelerant_assignment':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Axelerent Coding Assignement: Modify Site information form and add API key. Implement a custom route to get json response') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function axelerant_assignment_form_system_site_information_settings_alter(&$form, FormStateInterface $form_state, $form_id) {
  $site_config = Drupal::config('system.site');
	$form['site_api'] = [
		'#type' => 'details',
		'#title' => t('Site API Details'),
		'#open' => TRUE,
	];
	
	$default_value = \Drupal::configFactory()->getEditable('system.site')->get('siteapikey');
	
	$form['site_api']['siteapikey'] = [
		'#type' => 'textfield',
		'#title' => t('Site API Key'),
		'#default_value' => $default_value,
		'#size' => 60,
		'#description' => t("The <em>From</em> stores the site API key"),
		'#attributes' => array(
       'placeholder' => t('No API Key yet'),
     ),
	];
	
	$form['actions']['submit']['#value'] = t('Update Configuration');
	$form['#submit'][] = 'axelerant_assignment_system_site_information_settings_form_submit';
}

/**
 * Implements custom submit handler.
 */
function axelerant_assignment_system_site_information_settings_form_submit(&$form, FormStateInterface $form_state) {
	\Drupal::configFactory()->getEditable('system.site')
    ->set('siteapikey', $form_state->getValue('siteapikey'))
    ->save();
	
	$site_api_value = ($form_state->getValue('siteapikey')) ? $form_state->getValue('siteapikey') : 'blank';
	\Drupal::messenger()->addMessage(t('Site API Key has been saved with %siteapikey value.', ['%siteapikey' => $site_api_value]));
}